services:
  jupyter:
    build:
      context: .
    ports:
      - 8888:8888
    volumes:
      - ./project:/project
    command: jupyter lab --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=''
